# Generated by Django 4.1 on 2022-08-09 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_facebook', models.URLField(default='instagram', max_length=100)),
                ('social_youtube', models.URLField(blank=True, max_length=100, null=True)),
                ('social_telegram', models.URLField(blank=True, max_length=100, null=True)),
                ('social_instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('admin', 'admin')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio')),
                ('comment_count', models.IntegerField(default=0)),
                ('students_count', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
