# Generated by Django 4.1 on 2022-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiles_social_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='teachers_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
