# Generated by Django 4.1 on 2022-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profiles_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
