# Generated by Django 4.1 on 2022-08-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
