# Generated by Django 4.1 on 2022-08-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_social_facebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='full_name',
            new_name='user_username',
        ),
    ]
