# Generated by Django 4.1 on 2022-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profiles_social_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
