# Generated by Django 4.1 on 2022-11-18 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='student_id',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, help_text='(fakhriyor)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=998, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +9981234567 formatida bo'lishi kerak", regex='^998\\d{9}$')]),
        ),
    ]
