# Generated by Django 4.0.5 on 2022-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_theme_theme_user_order_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course_category',
        ),
        migrations.AddField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='duration',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='conversation',
            field=models.FileField(blank=True, upload_to='homework_conv'),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='dictionary',
            field=models.FileField(blank=True, upload_to='homework_dict'),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='exercise',
            field=models.ImageField(blank=True, upload_to='homework_ex'),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme_user',
            name='translation',
            field=models.FileField(blank=True, upload_to='homework_translation'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='bought_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
