# Generated by Django 4.1 on 2022-11-18 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=998, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998121231212 formatida bo'lishi kerak", regex='^+998\\d{9}$')]),
        ),
    ]
